language: node_js
node_js:
  - '8'
dist: trusty
sudo: false
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn test --runInBand --no-cache
  - yarn release
cache:
  directories:
    - node_modules
